services:
  - type: web
    name: codemind
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: openai/gpt-oss-120b
      - key: EMBEDDING_MODEL
        value: all-MiniLM-L6-v2
